export const FETCH_COMMIT_HISTORY = 'FETCH_COMMIT_HISTORY';
//BAR CHART SELECT FILE
export const BAR_CHART_FILE_DATA = 'BAR_CHART_FILE_DATA';
export const BAR_CHART_FILE_SELECTED = 'BAR_CHART_FILE_SELECTED';
//DOUGHNUT CHART TICKET TYPE
export const DOUGHNUT_COMMIT_PRIORITY_DATA = 'DOUGHNUT_COMMIT_PRIORITY_DATA';
export const DOUGHNUT_COMMIT_PRIORITY_SELECTED = 'DOUGHNUT_COMMIT_PRIORITY_PRIORITY_SELECTED';
//DOUGHNUT CHART TICKET TYPE
export const DOUGHNUT_TICKET_TYPE_DATA = 'DOUGHNUT_CHART_TICKET_TYPE_DATA';
export const DOUGHNUT_TICKET_TYPE_DATA_SELECTED = 'DOUGHNUT_TICKET_TYPE_DATA_SELECTED';
//LINE DATA INSIGHTS
export const LINE_DATA_INSIGHTS_DATA = 'LINE_DATA_SIGHTS_DATA';
//TABLE DATA INSIGHTS
export const TABLE_DATA_INSIGHTS_DATA = 'TABLE_DATA_SIGHTS_DATA';
